services:
  - type: web
    name: cu-bot
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: KEEP_ALIVE_ENABLED
        value: "true"
      - key: BOT_KEY
        value: "main"
      - key: DATA_REFRESH_SECONDS
        value: "120"
