-- CU BOT - GENERATED FROM YOUR GOOGLE SHEET TEMPLATE.XLSX
-- Source: /Users/hminhnhut/Downloads/cu_bot_google_sheet_template.xlsx
-- Run in Supabase Dashboard -> SQL Editor.
-- WARNING: This resets these bot tables before inserting cleaned data.

begin;

drop table if exists video_messages cascade;
drop table if exists bot_allowlist cascade;
drop table if exists admins cascade;
drop table if exists keywords cascade;
drop table if exists messages cascade;
drop table if exists config cascade;
drop table if exists groups cascade;

create table groups (
  id bigserial primary key,
  group_id text not null,
  group_name text,
  enabled boolean not null default true,
  delete_system_messages boolean,
  delete_forwarded_messages boolean,
  delete_inline_keyboard_messages boolean,
  delete_messages_from_bots boolean,
  remove_unknown_bots boolean,
  exempt_admins boolean,
  spam_max_messages integer,
  spam_window_seconds integer,
  spam_action text,
  forward_action text,
  inline_keyboard_action text,
  ban_after_warnings integer,
  warning_text text,
  daily_enabled boolean,
  daily_window_start text,
  daily_window_end text,
  send_if_silent boolean,
  message_pool text,
  video_enabled boolean,
  video_window_start text,
  video_window_end text,
  video_pool text,
  policy_text text,
  notes text
);

create table config (
  id bigserial primary key,
  key text not null unique,
  value text,
  enabled boolean not null default true,
  notes text
);

create table messages (
  id bigserial primary key,
  message text not null,
  pool text not null default 'default',
  weight integer not null default 1,
  enabled boolean not null default true,
  notes text
);

create table keywords (
  id bigserial primary key,
  keyword text not null,
  match text not null default 'contains',
  action text not null default 'warn',
  reason text,
  enabled boolean not null default true,
  notes text
);

create table admins (
  id bigserial primary key,
  user_id text not null,
  chat_id text,
  enabled boolean not null default true,
  notes text
);

create table bot_allowlist (
  id bigserial primary key,
  bot_id text,
  username text,
  chat_id text,
  enabled boolean not null default true,
  notes text
);

create table video_messages (
  id bigserial primary key,
  from_chat_id text not null,
  message_id text not null,
  caption text,
  pool text not null default 'default',
  weight integer not null default 1,
  enabled boolean not null default true,
  notes text
);

create index groups_enabled_group_id_idx on groups (enabled, group_id);
create index config_enabled_key_idx on config (enabled, key);
create index messages_enabled_pool_idx on messages (enabled, pool);
create index keywords_enabled_idx on keywords (enabled);
create index admins_enabled_chat_idx on admins (enabled, chat_id);
create index bot_allowlist_enabled_chat_idx on bot_allowlist (enabled, chat_id);
create index video_messages_enabled_pool_idx on video_messages (enabled, pool);

alter table groups enable row level security;
alter table config enable row level security;
alter table messages enable row level security;
alter table keywords enable row level security;
alter table admins enable row level security;
alter table bot_allowlist enable row level security;
alter table video_messages enable row level security;

-- Service role keys bypass RLS. Keep SUPABASE_SERVICE_ROLE_KEY server-side only.

insert into groups (group_id, group_name, enabled, delete_system_messages, delete_forwarded_messages, delete_inline_keyboard_messages, delete_messages_from_bots, remove_unknown_bots, exempt_admins, spam_max_messages, spam_window_seconds, spam_action, forward_action, inline_keyboard_action, ban_after_warnings, warning_text, daily_enabled, daily_window_start, daily_window_end, send_if_silent, message_pool, video_enabled, video_window_start, video_window_end, video_pool, policy_text, notes) values
  ('-1002151486481', 'Hang Cú chat', true, true, true, true, true, true, true, 3, 12, 'warn', 'warn', 'warn', 3, '⚠️ Cảnh báo: {reason} ({count}/{limit})', true, '20:00', '23:59', false, 'default', true, '21:00', '23:00', 'default', '📌 <b>NỘI QUY GROUP CHAT</b>

• Tôn trọng mọi thành viên trong group  
• Không spam, flood hoặc gửi link rác  
• Không leak, reup hay chia sẻ nội dung ra bên ngoài  
• Không quảng cáo, kéo member hoặc bán hàng khi chưa được phép  
• Hạn chế gây war, toxic hoặc làm ảnh hưởng trải nghiệm chung  
• Admin có quyền mute/kick/ban vĩnh viễn nếu vi phạm

💎 Giữ group văn minh để mọi người có trải nghiệm tốt nhất.', 'Doi group_id thanh group that'),
  ('-1002151486481', 'Group phu', false, true, true, true, true, true, true, 8, 15, 'delete', 'delete', 'warn', 3, '⚠️ Cảnh báo: {reason} ({count}/{limit})', true, '19:00', '22:00', true, 'sales', false, '21:00', '23:00', 'default', null, 'Dong mau, co the xoa');

insert into config (key, value, enabled) values
  ('policy_text', '📌 <b>NỘI QUY GROUP CHAT</b>

• Tôn trọng mọi thành viên trong group  
• Không spam, flood hoặc gửi link rác  
• Không leak, reup hay chia sẻ nội dung ra bên ngoài  
• Không quảng cáo, kéo member hoặc bán hàng khi chưa được phép  
• Hạn chế gây war, toxic hoặc làm ảnh hưởng trải nghiệm chung  
• Admin có quyền mute/kick/ban vĩnh viễn nếu vi phạm

💎 Giữ group văn minh để mọi người có trải nghiệm tốt nhất.', true),
  ('delete_system_messages', 'true', true),
  ('delete_forwarded_messages', 'true', true),
  ('delete_inline_keyboard_messages', 'true', true),
  ('delete_messages_from_bots', 'true', true),
  ('remove_unknown_bots', 'true', true),
  ('scan_bio_links', 'true', true),
  ('bio_scan_cache_seconds', '3600', true),
  ('bio_link_restrict_seconds', '0', true),
  ('bio_link_warning_text', '{mention} ơi, vui lòng gỡ link trên bio rồi liên hệ admin để mở chat trở lại nhen!', true),
  ('exempt_admins', 'true', true),
  ('spam_max_messages', '3', true),
  ('spam_window_seconds', '12', true),
  ('spam_action', 'warn', true),
  ('forward_action', 'warn', true),
  ('inline_keyboard_action', 'warn', true),
  ('ban_after_warnings', '3', true),
  ('daily_window_start', '20:00', true),
  ('daily_window_end', '23:59', true),
  ('send_if_silent', 'false', true),
  ('send_on_boot', 'false', true);

insert into messages (message, pool, weight, enabled) values
  ('Câu nói dâm dục', 'default', 1, false),
  ('Ông xã ơi cặc anh cứng chưa? Em thèm bú lắm', 'default', 1, true),
  ('Anh yêu ơi em nứng đít quá, anh đụ em đi', 'default', 1, true),
  ('Mấy anh chồng ơi ai cho em bú cu ngay bây giờ?', 'default', 1, true),
  ('Ông xã em van anh, nhét cu vào đít em đi', 'default', 1, true),
  ('Anh yêu ơi đít em ướt nhẹp rồi, anh vào đi', 'default', 1, false),
  ('Chồng ơi cặc anh to quá, em thèm nuốt hết', 'default', 1, true),
  ('Mấy anh ơi em cong mông chờ anh đụ đây', 'default', 1, true),
  ('Ông xã ơi đổ tinh nóng vào trong em đi', 'default', 1, true),
  ('Anh yêu em đang co thắt gọi cu anh nè', 'default', 1, true),
  ('Chồng ơi anh đụ em mạnh tay đi em xin anh', 'default', 1, false),
  ('Em là vợ dâm của anh, anh dùng em thả ga', 'default', 1, true),
  ('Ông xã ơi liếm lỗ đít em rồi đụ em nha', 'default', 1, true),
  ('Anh yêu ơi em thèm cu anh nhét sâu lắm', 'default', 1, true),
  ('Mấy anh chồng ơi ai muốn đụ em từ sau?', 'default', 1, true),
  ('Chồng ơi bắn tinh đầy đít em đi em van anh', 'default', 1, false),
  ('Ông xã em nứng run cả người rồi, anh cứu em', 'default', 1, true),
  ('Anh yêu ơi cặc anh giật giật em muốn bú', 'default', 1, true),
  ('Em cong mông cao mời cu anh vào đây', 'default', 1, true),
  ('Ông xã ơi em chỉ dành lỗ đít cho anh thôi', 'default', 1, true),
  ('Chồng ơi anh đụ em đến khi em run người đi', 'default', 1, false),
  ('Anh yêu ơi em thèm tinh anh nóng bỏng quá', 'default', 1, true),
  ('Mấy anh ơi ai cho em bú cu sạch sẽ?', 'default', 1, true),
  ('Ông xã em mặc hở đít chờ anh xem nè', 'default', 1, true),
  ('Anh yêu ơi nhét cu to vào em đi em chịu được', 'default', 1, true),
  ('Chồng ơi em sướng quá ư ư anh đừng dừng', 'default', 1, false),
  ('Ông xã ơi em van anh đụ mạnh nữa đi', 'default', 1, true),
  ('Anh yêu ơi đít em tròn căng mời anh đụ', 'default', 1, true),
  ('Mấy anh chồng ơi em thèm bị anh đổ tinh đầy', 'default', 1, true),
  ('Chồng ơi cặc anh dài em muốn ngậm hết', 'default', 1, true),
  ('Ông xã em đang ướt lỗ chờ cu anh đây', 'default', 1, false),
  ('Anh yêu ơi anh ôm em rồi đụ em mạnh đi', 'default', 1, true),
  ('Em là vợ ngoan chỉ biết van anh đụ', 'default', 1, true),
  ('Ông xã ơi liếm đít em đi em thích lắm', 'default', 1, true),
  ('Chồng ơi anh bắn tinh trong em rồi đụ tiếp', 'default', 1, true),
  ('Anh yêu ơi em nứng không ngủ nổi nữa', 'default', 1, false),
  ('Mấy anh ơi ai muốn thay phiên đụ em?', 'default', 1, true),
  ('Ông xã em cong mông lắc cho anh xem', 'default', 1, true),
  ('Anh yêu ơi cu anh cứng ngắc em bú ngay', 'default', 1, true),
  ('Chồng ơi em xin anh nhét sâu tận đáy', 'default', 1, true),
  ('Ông xã ơi em thèm bị anh dùng mạnh bạo', 'default', 1, false),
  ('Anh yêu ơi đổ tinh nóng vào ruột em đi', 'default', 1, true),
  ('Mấy anh chồng ơi em sẵn sàng bị anh đụ', 'default', 1, true),
  ('Chồng ơi anh dừng lại đi… aaaa mạnh nữa', 'default', 1, true),
  ('Ông xã em bú cu anh đến khi anh xịt', 'default', 1, true),
  ('Anh yêu ơi lỗ em co thắt gọi anh', 'default', 1, false),
  ('Em van mấy anh đụ em thật sâu đi', 'default', 1, true),
  ('Ông xã ơi em thèm cu anh trong người lắm', 'default', 1, true),
  ('Chồng ơi anh đụ em doggy em lắc mông', 'default', 1, true),
  ('Anh yêu ơi em là con đĩ của anh mà', 'default', 1, true),
  ('Ông xã ơi bắn tinh đầy miệng em nha', 'default', 1, false),
  ('Mấy anh ơi ai muốn đụ em liên tục?', 'default', 1, true),
  ('Chồng ơi đít em mướt nước chờ anh', 'default', 1, true),
  ('Anh yêu ơi anh nhét hai ngón trước đi', 'default', 1, true),
  ('Ông xã em thèm bị anh ôm chặt đụ', 'default', 1, true),
  ('Chồng ơi em sướng run chân vì anh', 'default', 1, false),
  ('Anh yêu ơi cu anh to làm em mê luôn', 'default', 1, true),
  ('Ông xã ơi em xin anh đừng rút ra', 'default', 1, true),
  ('Mấy anh chồng ơi em chờ anh nhét cu vào', 'default', 1, true),
  ('Chồng ơi anh liếm lỗ em rồi đụ mạnh', 'default', 1, true),
  ('Anh yêu ơi em van anh bắn tinh nhiều lần', 'default', 1, false),
  ('Ông xã em cong mông cao mời anh', 'default', 1, true),
  ('Chồng ơi em chỉ là vợ dâm của anh', 'default', 1, true),
  ('Anh yêu ơi anh đụ em đến khóc vì sướng', 'default', 1, true),
  ('Ông xã ơi em thèm tinh anh nóng hổi', 'default', 1, true),
  ('Mấy anh ơi ai cho em bú cu sáng nay?', 'default', 1, false),
  ('Chồng ơi đít em ngứa lắm anh chữa đi', 'default', 1, true),
  ('Anh yêu ơi em sẵn sàng quỳ bú anh', 'default', 1, true),
  ('Ông xã ơi anh đụ em từ từ rồi mạnh', 'default', 1, true),
  ('Em van anh đổ đầy tinh vào đít em', 'default', 1, true),
  ('Chồng ơi cặc anh ngon em liếm sạch', 'default', 1, false),
  ('Anh yêu ơi em nứng đít muốn nổ tung', 'default', 1, true),
  ('Ông xã ơi anh ôm em rồi nhét cu vào', 'default', 1, true),
  ('Mấy anh ơi em là vợ chung của anh', 'default', 1, true),
  ('Chồng ơi em thèm bị anh tát mông khi đụ', 'default', 1, true),
  ('Anh yêu ơi lỗ em giãn ra chờ anh', 'default', 1, false),
  ('Ông xã em bú cu anh thật lâu nha', 'default', 1, true),
  ('Chồng ơi anh bắn tinh rồi đổi tư thế', 'default', 1, true),
  ('Anh yêu ơi em xin anh dùng em thả ga', 'default', 1, true),
  ('Ông xã ơi em cong mông chờ anh từ sau', 'default', 1, true),
  ('Mấy anh ơi ai muốn nhét cu to vào em?', 'default', 1, false),
  ('Chồng ơi em sướng quá anh đụ mạnh nữa', 'default', 1, true),
  ('Anh yêu ơi tinh anh nóng em thích lắm', 'default', 1, true),
  ('Ông xã em van anh đừng dừng lại', 'default', 1, true),
  ('Chồng ơi em là vợ dâm ngoan của anh', 'default', 1, true),
  ('Anh yêu ơi cu anh cứng em muốn ngậm', 'default', 1, false),
  ('Ông xã ơi em ướt nhẹp hết cả đít', 'default', 1, true),
  ('Mấy anh ơi em thèm bị anh đụ mạnh', 'default', 1, true),
  ('Chồng ơi anh liếm đít em đi em mê', 'default', 1, true),
  ('Anh yêu ơi em xin anh bắn tinh đầy', 'default', 1, true),
  ('Ông xã ơi đít em tròn căng chờ anh', 'default', 1, false),
  ('Chồng ơi em van anh nhét sâu hơn nữa', 'default', 1, true),
  ('Anh yêu ơi em nứng vì anh cả ngày', 'default', 1, true),
  ('Ông xã em sẵn sàng bị anh dùng', 'default', 1, true),
  ('Mấy anh chồng ơi ai đụ em trước đây?', 'default', 1, true),
  ('Chồng ơi em thèm cu anh trong đít lắm', 'default', 1, false),
  ('Anh yêu ơi anh đụ em em rên tên anh', 'default', 1, true),
  ('Ông xã ơi em là đồ chơi của anh', 'default', 1, true),
  ('Chồng ơi anh bắn tinh nóng vào em đi', 'default', 1, true),
  ('Anh yêu ơi em cong mông mời anh nhét', 'default', 1, true),
  ('Ông xã em van anh đụ em không ngừng', 'default', 1, false),
  ('Ông xã ơi cặc anh cứng ngắc chưa? Em thèm bú cu lắm 🍆😩', 'default', 1, false),
  ('Anh yêu ơi đít em ướt nhẹp rồi, anh nhét cu vào mau đi 💦🍑', 'default', 1, false),
  ('Chồng ơi em nứng đít quá, anh đụ em mạnh tay đi 😭🔥', 'default', 1, false),
  ('Mấy anh chồng ơi ai cho em bú cu ngay bây giờ? 🍆💦', 'default', 1, false),
  ('Ông xã ơi đổ tinh nóng hổi đầy đít em đi 💦😈', 'default', 1, false),
  ('Anh yêu ơi cặc anh to quá, em muốn nuốt hết vào họng 🍆😛', 'default', 1, false),
  ('Chồng ơi em cong mông cao, anh đụ em từ sau đi 🍑🔥', 'default', 1, false),
  ('Ông xã ơi liếm lỗ đít em đi rồi nhét cu vào 😛🍑', 'default', 1, false),
  ('Anh yêu ơi em van anh đụ mạnh nữa, em sướng quá ư ư 😩💦', 'default', 1, false),
  ('Mấy anh ơi em là vợ dâm, ai muốn bắn tinh đầy em? 💦🍑', 'default', 1, false),
  ('Chồng ơi đít em co thắt gọi cặc anh, anh vào đi 😭🍆', 'default', 1, false),
  ('Ông xã ơi em thèm cu anh nhét sâu tận ruột 💦🔥', 'default', 1, false),
  ('Anh yêu ơi bắn tinh đầy miệng em, em nuốt sạch nha 😛💦', 'default', 1, false),
  ('Chồng ơi anh đụ em đến khi em run cả chân đi 😩🍑', 'default', 1, false),
  ('Ông xã ơi em mặc hở đít chờ anh nhét cu 🍑😈', 'default', 1, false),
  ('Anh yêu ơi cặc anh giật giật, em muốn bú sạch 🍆💦', 'default', 1, false),
  ('Mấy anh chồng ơi ai muốn đụ em liên tục không nghỉ? 🔥😭', 'default', 1, false),
  ('Ông xã ơi em xin anh nhét cu to giãn lỗ em ra 🍆🍑', 'default', 1, false),
  ('Chồng ơi em nứng vl, anh đụ em mạnh bạo đi 😈💦', 'default', 1, false),
  ('Anh yêu ơi đổ tinh nóng vào trong đít em đầy luôn 💦😩', 'default', 1, false),
  ('Ông xã ơi em cong mông lắc lư mời anh đụ 🍑🔥', 'default', 1, false),
  ('Chồng ơi anh liếm đít em thật sâu đi em mê 😛🍑', 'default', 1, false),
  ('Anh yêu ơi em thèm bị anh dùng như con đĩ 😈💕', 'default', 1, false),
  ('Ông xã ơi cặc anh cứng em bú ngay bây giờ 🍆😛', 'default', 1, false),
  ('Mấy anh ơi em van anh bắn tinh nhiều lần vào em 💦🍑', 'default', 1, false),
  ('Chồng ơi đít em tròn căng mướt, anh sờ và đụ đi 🍑💦', 'default', 1, false),
  ('Anh yêu ơi em sướng quá aaaa anh đừng dừng lại 😭🔥', 'default', 1, false),
  ('Ông xã ơi em chỉ là lỗ đít dành cho anh đụ thôi 🍑😩', 'default', 1, false),
  ('Chồng ơi anh nhét cu sâu nữa đi, em chịu được hết 💦😈', 'default', 1, false),
  ('Anh yêu ơi em thèm tinh anh nóng bỏng bắn đầy ruột 💦🍆', 'default', 1, false),
  ('Ông xã ơi em quỳ sẵn chờ anh đụ mạnh 🍑🔥', 'default', 1, false),
  ('Mấy anh chồng ơi ai muốn thay phiên đụ em? 😈💦', 'default', 1, false),
  ('Chồng ơi em bú cu anh đến khi anh xịt tinh đầy miệng 😛💦', 'default', 1, false),
  ('Anh yêu ơi lỗ em co thắt thèm cặc anh quá 😩🍆', 'default', 1, false),
  ('Ông xã ơi anh đụ em doggy em lắc mông cho anh 🍑😘', 'default', 1, false),
  ('Chồng ơi em nứng không ngủ nổi, anh cứu em bằng cu đi 🍆💦', 'default', 1, false),
  ('Anh yêu ơi bắn tinh lên mặt em đi, em há miệng chờ 😛💦', 'default', 1, false),
  ('Ông xã ơi em thèm bị anh tát mông khi đụ 😈🍑', 'default', 1, false),
  ('Mấy anh ơi em là vợ dâm chung, ai muốn đụ em? 🔥💦', 'default', 1, false),
  ('Chồng ơi anh ôm em chặt rồi nhét cu vào mạnh đi 😩💕', 'default', 1, false),
  ('Anh yêu ơi em xin anh creampie em liên tục 💦🍑', 'default', 1, false),
  ('Ông xã ơi đít em ngứa lắm, anh chữa bằng cu to đi 🍆😭', 'default', 1, false),
  ('Chồng ơi em van anh đụ em không ngừng nghỉ 🔥💦', 'default', 1, false),
  ('Anh yêu ơi cặc anh khấc to làm em mê mẩn 🍆😩', 'default', 1, false),
  ('Ông xã ơi em cong mông cao mời anh nhét hết 🍑💦', 'default', 1, false),
  ('Mấy anh chồng ơi ai cho em bú hai cu cùng lúc? 🍆🍆', 'default', 1, false),
  ('Chồng ơi em sướng run người vì cu anh rồi 😭🔥', 'default', 1, false),
  ('Anh yêu ơi anh dừng lại đi… aaaa mạnh tay nữa đi 😩💦', 'default', 1, false),
  ('Ông xã ơi em thèm cu anh chạm tận đáy lỗ em 🍆🍑', 'default', 1, false),
  ('Chồng ơi em bú sạch cu anh rồi anh đụ em nha 😛💦', 'default', 1, false),
  ('Anh yêu ơi em là con đĩ bottom của anh mà 😈💕', 'default', 1, false),
  ('Ông xã ơi đổ tinh nóng vào đít em rồi đụ tiếp 💦🔥', 'default', 1, false),
  ('Mấy anh ơi em mặc quần lót hở, ai muốn xem lỗ em? 🍑😈', 'default', 1, false),
  ('Chồng ơi anh liếm đít em đi em ướt hết rồi 😛💦', 'default', 1, false),
  ('Anh yêu ơi em van anh dùng em thô bạo đi 😩🔥', 'default', 1, false),
  ('Ông xã ơi cặc anh cứng ngắc em muốn ngậm hết 🍆😛', 'default', 1, false),
  ('Chồng ơi em thèm bị anh bắn tinh đầy người 💦🍑', 'default', 1, false),
  ('Anh yêu ơi lỗ em giãn rộng chờ cu anh nhét vào 🍑💦', 'default', 1, false),
  ('Ông xã ơi em nứng đít muốn nổ tung rồi anh ơi 😭🍆', 'default', 1, false),
  ('Mấy anh ơi ai muốn đụ em standing position? 🔥💦', 'default', 1, false),
  ('Chồng ơi anh đụ em mạnh em rên tên anh nha 😩😈', 'default', 1, false),
  ('Anh yêu ơi em xin anh bắn tinh nóng hổi vào trong 💦', 'default', 1, false),
  ('Ông xã ơi em cong mông chờ anh từ đằng sau 🍑💕', 'default', 1, false),
  ('Chồng ơi em thèm tinh anh tràn ra khỏi đít 😭💦', 'default', 1, false),
  ('Anh yêu ơi cu anh ngon quá em liếm mãi không chán 🍆😛', 'default', 1, false),
  ('Ông xã ơi em sẵn sàng bị anh đụ bất cứ lúc nào 🔥', 'default', 1, false),
  ('Mấy anh chồng ơi em van anh nhét cu to vào mạnh 💦🍑', 'default', 1, false),
  ('Chồng ơi anh ôm em rồi đụ em thật sâu đi 😩💕', 'default', 1, false),
  ('Anh yêu ơi em là vợ dâm chỉ biết xin anh đụ 🍆😈', 'default', 1, false),
  ('Ông xã ơi em ướt nhẹp hết cả đít chờ anh 🍑💦', 'default', 1, false),
  ('Chồng ơi anh bắn tinh đầy ruột em đi em xin anh 💦😭', 'default', 1, false),
  ('Anh yêu ơi em thèm bị anh dùng như đồ chơi tình dục 😈', 'default', 1, false),
  ('Ông xã ơi cặc anh to em sợ mà thèm lắm 🍆💦', 'default', 1, false),
  ('Mấy anh ơi ai muốn creampie đít em hôm nay? 💦🍑', 'default', 1, false),
  ('Chồng ơi em bú cu anh thật lâu anh sướng không? 😛🔥', 'default', 1, false),
  ('Anh yêu ơi anh đụ em đến khi em khóc vì sướng 😩💦', 'default', 1, false),
  ('Ông xã ơi em cong mông lắc mời anh nhét cu 🍑😘', 'default', 1, false),
  ('Chồng ơi em van anh đừng rút cu ra ngoài 💦😭', 'default', 1, false),
  ('Anh yêu ơi em nứng vì cu anh cả ngày rồi 🍆🔥', 'default', 1, false),
  ('Ông xã ơi liếm lỗ đít em rồi đụ mạnh tay đi 😛🍑', 'default', 1, false),
  ('Mấy anh chồng ơi em thèm bị mấy anh đụ cùng lúc 😈💦', 'default', 1, false),
  ('Chồng ơi em sướng quá ư ư anh đụ mạnh nữa đi 😩🔥', 'default', 1, false),
  ('Anh yêu ơi em xin anh tinh đầy miệng và đầy đít 💦😛', 'default', 1, false),
  ('Ông xã ơi đít em tròn căng mướt mời anh dùng 🍑💕', 'default', 1, false),
  ('Chồng ơi anh nhét cu vào em rồi bắn tinh luôn đi 🍆💦', 'default', 1, false),
  ('Anh yêu ơi em là vợ dâm ngoan của anh mà 😘😈', 'default', 1, false),
  ('Ông xã ơi em thèm cu anh giật trong đít em 🍆😩', 'default', 1, false),
  ('Mấy anh ơi ai muốn đụ em rồi bắn tinh đầy? 💦🍑', 'default', 1, false),
  ('Chồng ơi em van anh dùng em thả ga đêm nay 🔥😭', 'default', 1, false),
  ('Anh yêu ơi hành hạ em đi, đụ em thật mạnh bạo 😭💦', null, null, null),
  ('Ông xã ơi dùng em như con đĩ, hành hạ em thô bạo đi 🍑😈', null, null, null),
  ('Chồng ơi hành hạ đít em đi, đụ mạnh đến xé luôn 🔥😩', null, null, null),
  ('Mấy anh ơi hành hạ em mạnh tay, em xin mấy anh 💦🍆', null, null, null),
  ('Anh yêu ơi tát mông em đỏ lên rồi đụ em 😈🍑', null, null, null),
  ('Ông xã ơi hành hạ em bằng cu to, nhét mạnh vào đi 😭🔥', null, null, null),
  ('Chồng ơi em muốn bị anh hành hạ đến khóc luôn 💦😩', null, null, null),
  ('Anh yêu ơi bóp cổ em nhẹ rồi đụ mạnh em đi 😈💦', null, null, null),
  ('Ông xã ơi hành hạ vợ dâm của anh đi, dùng em thả ga 🍑🔥', null, null, null),
  ('Mấy anh chồng ơi hành hạ em chung, đụ em không thương tiếc 😭', null, null, null),
  ('Chồng ơi kéo tóc em rồi đụ từ sau mạnh bạo đi 🍆💦', null, null, null),
  ('Anh yêu ơi hành hạ lỗ đít em, đụ đến sưng luôn 😩🍑', null, null, null),
  ('Ông xã ơi em xin anh hành hạ em thật đau sướng 🔥😈', null, null, null),
  ('Chồng ơi tát em vài cái rồi nhét cu to vào 💦😭', null, null, null),
  ('Anh yêu ơi hành hạ em như con thú, đụ không ngừng 🍑😈', null, null, null),
  ('Ông xã ơi bắn tinh xong đừng rút, tiếp tục hành hạ em 💦🔥', null, null, null),
  ('Mấy anh ơi hành hạ em bằng cách thay phiên đụ mạnh 😩🍆', null, null, null),
  ('Chồng ơi em muốn bị anh hành hạ đến run rẩy luôn 😭💦', null, null, null),
  ('Anh yêu ơi cắn vai em rồi đụ thật sâu mạnh tay 🍑😈', null, null, null),
  ('Ông xã ơi hành hạ đít em bằng cu khấc to đi 🔥💦', null, null, null),
  ('Chồng ơi em là đồ chơi của anh, hành hạ em thô bạo 😩😈', null, null, null),
  ('Anh yêu ơi nhét mạnh cu vào, hành hạ em đến mệt mỏi 💦🍑', null, null, null),
  ('Ông xã ơi hành hạ em bằng cách đụ liên tục không nghỉ 😭🔥', null, null, null),
  ('Mấy anh ơi dùng em mạnh bạo, hành hạ vợ dâm đi 🍆💦', null, null, null),
  ('Chồng ơi tát nhẹ cặc em rồi đụ mạnh lỗ đít 😈😩', null, null, null),
  ('Anh yêu ơi hành hạ em đi, em muốn đau vì sướng 🍑💦', null, null, null),
  ('Ông xã ơi kéo tay em ra sau rồi đụ như chó 🔥😭', null, null, null),
  ('Chồng ơi hành hạ em thật mạnh, em van anh 😩💦', null, null, null),
  ('Anh yêu ơi bắn tinh vào mặt em rồi tiếp tục hành hạ 😛😈', null, null, null),
  ('Ông xã ơi em xin anh hành hạ đít em đến sưng đỏ 🍑🔥', null, null, null),
  ('Mấy anh chồng ơi hành hạ em chung một lúc đi 💦🍆', null, null, null),
  ('Chồng ơi em thích bị anh hành hạ như con đĩ rẻ tiền 😈😭', null, null, null),
  ('Anh yêu ơi đụ em mạnh đến khi em khóc vì khoái lạc 💦🍑', null, null, null),
  ('Ông xã ơi hành hạ em bằng cu to và tay mạnh 🔥😩', null, null, null),
  ('Chồng ơi em muốn anh hành hạ em suốt đêm nay 😭💦', null, null, null),
  ('Anh yêu ơi bóp mông em mạnh rồi nhét sâu cu vào 🍑😈', null, null, null),
  ('Ông xã ơi hành hạ vợ anh đi, đụ em thô bạo không thương 🍆💦', null, null, null),
  ('Mấy anh ơi hành hạ em bằng cách đổ tinh đầy rồi đụ tiếp 😩🔥', null, null, null),
  ('Chồng ơi em van anh hành hạ em thật lực đi 😭💦', null, null, null),
  ('Anh yêu ơi dùng em như lỗ đít công cộng, hành hạ em 😈🍑', null, null, null),
  ('Ông xã ơi đụ em mạnh đến khi em không đứng nổi 🔥😩', null, null, null),
  ('Chồng ơi hành hạ em bằng roi nhẹ hoặc tay tát mông 💦😈', null, null, null),
  ('Anh yêu ơi em thèm bị anh hành hạ dã man 🍑😭', null, null, null),
  ('Ông xã ơi nhét cu thật mạnh, hành hạ lỗ em đi 💦🔥', null, null, null),
  ('Mấy anh chồng ơi hành hạ em cùng lúc, em chịu hết 😩🍆', null, null, null),
  ('Chồng ơi em là đồ chơi tình dục, anh hành hạ em đi 😈💦', null, null, null),
  ('Anh yêu ơi hành hạ em đến sướng phát điên luôn 🍑😭', null, null, null),
  ('Ông xã ơi đụ em mạnh bạo, em muốn bị anh làm nhục 💦😈', null, null, null),
  ('Chồng ơi hành hạ em ngay bây giờ đi, em nứng lắm rồi 🔥😩', null, null, null),
  ('Anh yêu ơi đít em to tròn căng mọng, anh đụ em đi 🍑💦', null, null, null),
  ('Ông xã ơi mông em căng tròn to lớn, anh nhét cu vào mau 😩🍑', null, null, null),
  ('Chồng ơi đào em to căng mướt, anh sờ và đụ mạnh đi 🔥🍑', null, null, null),
  ('Mấy anh ơi đít em tròn lẳn căng bóng, ai muốn đụ trước? 💦😈', null, null, null),
  ('Anh yêu ơi mông em to căng mời anh tát rồi đụ 🍑😭', null, null, null),
  ('Ông xã ơi đít em căng mọng như trái đào chín, anh đụ em 😩💦', null, null, null),
  ('Chồng ơi đào em to tròn mướt mát, anh nhét cu sâu đi 🍑🔥', null, null, null),
  ('Em van anh, đít em căng tròn to này chỉ chờ anh đụ 💦🍑', null, null, null),
  ('Anh yêu ơi mông em to căng rung rung, anh đụ từ sau đi 😈', null, null, null),
  ('Ông xã ơi đào em căng mọng ướt nhẹp, anh chữa cho em 🍑😩', null, null, null),
  ('Chồng ơi đít em tròn to căng bóng, anh muốn liếm không? 😛💦', null, null, null),
  ('Mấy anh chồng ơi mông em to căng mướt, ai nhét cu vào? 🔥🍑', null, null, null),
  ('Anh yêu ơi em cong đít to tròn lên cho anh ngắm 🍑😘', null, null, null),
  ('Ông xã ơi đào em căng tròn to lớn, anh đụ mạnh tay đi 😭💦', null, null, null),
  ('Chồng ơi mông em to căng mọng, anh tát đỏ rồi đụ 🍑😈', null, null, null),
  ('Anh yêu ơi đít em tròn lẳn căng mướt, anh nhét hết cu vào 💦', null, null, null),
  ('Ông xã ơi đào em to căng chờ anh, anh đụ em thô bạo đi 🔥😩', null, null, null),
  ('Em xin anh, mông em căng tròn to này anh dùng đi 🍑💦', null, null, null),
  ('Chồng ơi đít em to tròn mọng nước, anh liếm rồi đụ 😛🍑', null, null, null),
  ('Anh yêu ơi mông em căng bóng mời anh nhét cu mạnh 😈💦', null, null, null),
  ('Ông xã ơi đào em to căng rung lắc, anh đụ em doggy đi 🍑🔥', null, null, null),
  ('Chồng ơi đít em tròn to căng mọng, anh bắn tinh vào đi 💦😭', null, null, null),
  ('Mấy anh ơi mông em to căng mướt, ai muốn đụ chung? 😈🍑', null, null, null),
  ('Anh yêu ơi em cong mông to tròn cho anh xem lỗ 🍑😩', null, null, null),
  ('Ông xã ơi đào em căng tròn to lớn, anh đụ sâu tận đáy 💦', null, null, null),
  ('Chồng ơi đít em mọng nước căng bóng, anh hành hạ em đi 😈🍑', null, null, null),
  ('Anh yêu ơi mông em to tròn căng, anh ôm chặt rồi đụ 🔥💦', null, null, null),
  ('Ông xã ơi đào em căng mọng thèm cu anh, anh vào đi 😩🍆', null, null, null),
  ('Chồng ơi đít em tròn lẳn to căng, anh tát mạnh đi 🍑😭', null, null, null),
  ('Anh yêu ơi em lắc mông to căng mướt cho anh ngắm 😘💦', null, null, null),
  ('Ông xã ơi mông em căng tròn mời anh nhét cu to 🍑🔥', null, null, null),
  ('Mấy anh chồng ơi đít em to mọng, ai muốn đụ trước? 😈', null, null, null),
  ('Chồng ơi đào em căng bóng ướt át, anh đụ em mạnh bạo 💦🍑', null, null, null),
  ('Anh yêu ơi mông em tròn to căng mọng, anh dùng em đi 😩', null, null, null),
  ('Ông xã ơi đít em to căng rung khi anh đụ, anh thích không? 🍑💦', null, null, null),
  ('Chồng ơi em cong đào to tròn chờ anh nhét cu 🔥😭', null, null, null),
  ('Anh yêu ơi mông em căng mướt to lớn, anh liếm đít em 😛🍑', null, null, null),
  ('Ông xã ơi đào em tròn căng mọng nước, anh đụ em không ngừng 💦', null, null, null),
  ('Chồng ơi đít em to căng bóng, anh bắn tinh đầy vào đi 😈🍑', null, null, null),
  ('Anh yêu ơi em lắc mông to tròn cho anh nứng 🍑😘', null, null, null),
  ('Ông xã ơi mông em căng tròn to, anh hành hạ em mạnh đi 🔥😩', null, null, null),
  ('Mấy anh ơi đít em mọng căng mời anh nhét cu to 💦🍑', null, null, null),
  ('Chồng ơi đào em to tròn căng mướt, anh đụ em doggy 😈', null, null, null),
  ('Anh yêu ơi mông em căng bóng thèm bị anh tát 🍑💦', null, null, null),
  ('Ông xã ơi em cong đít to căng lên cho anh đụ 🍑😭', null, null, null),
  ('Chồng ơi đít em tròn lẳn mọng nước, anh nhét mạnh vào 🔥', null, null, null),
  ('Anh yêu ơi mông em to căng rung lắc, anh ôm em đụ 💦😩', null, null, null),
  ('Ông xã ơi đào em căng mọng chờ tinh anh đổ vào 🍑💦', null, null, null),
  ('Chồng ơi em van anh, dùng mông to căng của em đi 😈', null, null, null),
  ('Anh yêu ơi đít em to tròn căng, anh đụ em thật thô bạo 🔥🍑', null, null, null),
  ('Ông xã ơi mông em mướt mát căng mọng, anh liếm rồi đụ 😛💦', null, null, null),
  ('Chồng ơi đào em to căng mời anh nhét cu khấc to 🍆🍑', null, null, null),
  ('Anh yêu ơi em lắc đít to tròn cho anh xem 🍑😘', null, null, null),
  ('Ông xã ơi mông em căng bóng to lớn, anh dùng em thả ga 😈💦', null, null, null),
  ('Chồng ơi đít em tròn căng mọng, anh tát mạnh rồi đụ 🍑🔥', null, null, null),
  ('Anh yêu ơi đào em căng mướt ướt nhẹp chờ anh 😩💦', null, null, null),
  ('Ông xã ơi em cong mông to căng cao cho anh đụ 🍑😭', null, null, null),
  ('Mấy anh ơi đít em to mọng căng, ai muốn hành hạ em? 😈', null, null, null),
  ('Chồng ơi mông em tròn lẳn căng bóng, anh bắn tinh lên 🍑💦', null, null, null),
  ('Anh yêu ơi em thèm anh nhét cu vào đít to căng của em 🔥', null, null, null),
  ('Ông xã ơi đào em căng mọng to lớn, anh đụ em không thương tiếc 😩', null, null, null),
  ('Chồng ơi mông em to căng rung khi bị đụ mạnh 💦🍑', null, null, null),
  ('Anh yêu ơi đít em tròn căng mướt, anh liếm sạch đi 😛', null, null, null),
  ('Ông xã ơi em lắc mông to tròn mời anh nhét cu 🍑😈', null, null, null),
  ('Chồng ơi đào em căng bóng thèm cu anh lắm 😭💦', null, null, null),
  ('Anh yêu ơi mông em to căng mọng, anh ôm chặt hành hạ em 🔥', null, null, null),
  ('Ông xã ơi đít em tròn to căng, anh đụ em đến sưng 🍑😩', null, null, null),
  ('Chồng ơi em cong đào to mướt cho anh xem lỗ 💦🍑', null, null, null),
  ('Anh yêu ơi mông em căng tròn mời anh tát và đụ 😈', null, null, null),
  ('Ông xã ơi đít em to căng mọng nước, anh đổ tinh vào đi 💦', null, null, null),
  ('Chồng ơi em van anh dùng mông to tròn căng của em 🍑🔥', null, null, null),
  ('Anh yêu ơi đào em căng mướt to lớn chờ anh nhét 🍆😩', null, null, null),
  ('Ông xã ơi mông em tròn lẳn căng bóng, anh thích không? 😘💦', null, null, null),
  ('Chồng ơi em lắc đít to căng cho anh nứng mạnh 🍑😈', null, null, null),
  ('Anh yêu ơi đít em mọng căng thèm bị anh đụ mạnh 💦😭', null, null, null),
  ('Ông xã ơi đào em to tròn căng, anh hành hạ em đi 🔥🍑', null, null, null),
  ('Chồng ơi mông em căng mướt mời anh nhét cu sâu 🍑💦', null, null, null),
  ('Anh yêu ơi em cong mông to căng cao chờ anh 😩😈', null, null, null),
  ('Ông xã ơi đít em tròn to mọng, anh bắn tinh đầy ruột 💦', null, null, null),
  ('Chồng ơi đào em căng bóng ướt át, anh đụ em thô bạo 🍑🔥', null, null, null),
  ('Anh yêu ơi mông em to căng rung lắc, anh ôm em đi 😘', null, null, null),
  ('Ông xã ơi em thèm anh tát mông to căng của em 😈💦', null, null, null),
  ('Chồng ơi đít em tròn căng mọng nước mời anh 🍑😩', null, null, null),
  ('Anh yêu ơi mông em to lẳn căng, anh dùng em mạnh tay 🔥', null, null, null),
  ('Ông xã ơi đào em căng mướt to, anh nhét cu vào ngay 💦🍑', null, null, null),
  ('Chồng ơi em lắc đít to tròn cho anh xem 🍑😛', null, null, null),
  ('Anh yêu ơi mông em căng bóng thèm tinh anh đổ vào 😭💦', null, null, null),
  ('Ông xã ơi đít em to căng mọng, anh hành hạ em thả ga 😈🍑', null, null, null),
  ('Chồng ơi đào em tròn lẳn căng mời anh đụ mạnh 🔥', null, null, null),
  ('Anh yêu ơi em cong mông to căng chờ cu anh nhét 🍑💦', null, null, null),
  ('Ông xã ơi mông em căng mướt to lớn, anh liếm rồi đụ 😛😩', null, null, null);

insert into keywords (keyword, match, action, reason, enabled) values
  ('casino', 'contains', 'warn', 'Từ khóa cấm', true),
  ('telegram.me/', 'contains', 'delete', 'Link spam', true),
  ('t.me/spam', 'contains', 'ban', 'Link spam', true),
  ('free money', 'contains', 'warn', 'Nội dung spam', true),
  ('telegram\.me/', 'regex', 'delete', 'Từ khóa cấm', false),
  ('kid', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('kids', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('trẻ em', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('học sinh', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('đụ', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('k.i.d', 'contains', 'delete', 'Từ khóa nhạy cảm', true),
  ('crypto', 'contains', 'delete', 'Từ khóa cấm', true),
  ('miễn phí', 'contains', 'delete', 'Từ khóa cấm', true),
  ('free', 'contains', 'delete', 'Từ khóa cấm', true),
  ('kiếm tiền', 'contains', 'delete', 'Từ khóa cấm', true),
  ('làm giàu', 'contains', 'delete', 'Từ khóa cấm', true),
  ('đầu tư', 'contains', 'delete', 'Từ khóa cấm', true),
  ('coin', 'contains', 'delete', 'Từ khóa cấm', true),
  ('forex', 'contains', 'delete', 'Từ khóa cấm', true),
  ('bet', 'contains', 'delete', 'Từ khóa cấm', true),
  ('cá cược', 'contains', 'delete', 'Từ khóa cấm', true),
  ('tài xỉu', 'contains', 'delete', 'Từ khóa cấm', true),
  ('ref', 'contains', 'delete', 'Từ khóa cấm', true),
  ('airdrop', 'contains', 'delete', 'Từ khóa cấm', true),
  ('wa.me', 'contains', 'delete', 'Từ khóa cấm', true),
  ('t.me/', 'contains', 'delete', 'Từ khóa cấm', true),
  ('book kèo', 'contains', 'delete', 'Từ khóa cấm', true),
  ('shopee', 'contains', 'delete', 'Từ khóa cấm', true),
  ('zalo', 'contains', 'delete', 'Từ khóa cấm', true),
  ('.xxx', 'contains', 'delete', 'Từ khóa cấm', true),
  ('.apk', 'contains', 'delete', 'Từ khóa cấm', true),
  ('hack', 'contains', 'delete', 'Từ khóa cấm', true),
  ('crack', 'contains', 'delete', 'Từ khóa cấm', true),
  ('mod', 'contains', 'delete', 'Từ khóa cấm', true),
  ('sex', 'contains', 'delete', 'Từ khóa cấm', true),
  ('camsex', 'contains', 'delete', 'Từ khóa cấm', true),
  ('escort', 'contains', 'delete', 'Từ khóa cấm', true);

insert into admins (user_id, chat_id, enabled, notes) values
  ('887869657', '-1001234567890', true, 'Nhựt'),
  ('7344961485', null, true, 'thám tử'),
  ('5080922525', null, true, 'helio');

insert into bot_allowlist (bot_id, username, chat_id, enabled) values
  ('123456789', 'helpful_bot', '-1001234567890', true);

insert into video_messages (from_chat_id, message_id, caption, pool, weight, enabled) values
  ('-1009876543210', '456', 'Video hom nay', 'default', 1, false),
  ('-1009876543210', '789', null, 'default', 2, false);

commit;

-- Imported row counts:
-- groups: 2
-- config: 21
-- messages: 330
-- keywords: 37
-- admins: 3
-- bot_allowlist: 1
-- video_messages: 2