export const UI_COPY = {
  workbench: {
    automation: {
      eyebrow: "Automation",
      title: "Lịch gửi",
      body: "Chọn bot, group, pool.",
      action: "Mở wizard",
      readiness: "Trạng thái",
      ready: "Sẵn sàng",
      check: "Cần kiểm tra",
      bot: "Bot",
      group: "Group",
      tin: "Tin",
      video: "Video",
      missingBot: "Thiếu bot",
      missingGroup: "Thiếu group",
      missingTin: "Thiếu tin",
      missingVideo: "Thiếu video",
      schedule: "Lịch",
      scheduleReady: "Sẵn sàng",
      schedulePending: "cần xử lý",
      poolMessages: "Pool tin nhắn",
      poolVideos: "Pool video",
      open: "Mở",
      addMessages: "Thêm tin",
      addVideos: "Thêm video",
      setTime: "Đặt giờ",
      addGroup: "Thêm group",
      noMessages: "Chưa có tin.",
      noVideos: "Chưa có video.",
      choosePool: "Chưa chọn",
      tinCount: "tin",
      videoCount: "video",
      groupLabel: "Group",
      hourLabel: "Giờ"
    },
    moderation: {
      eyebrow: "Moderation",
      title: "Bảo vệ",
      body: "Chọn group rồi cấu hình luật.",
      ready: "Sẵn sàng",
      step1Title: "Luật",
      step1Body: "Spam, link, bot.",
      step2Title: "Test",
      step2Body: "Paste nội dung.",
      step3Title: "Logs",
      step3Body: "Xem xử lý.",
      open: "Mở",
      test: "Test",
      logs: "Logs",
      openProtection: "Mở bảo vệ",
      dangerousLinks: "Link nguy hiểm",
      botExceptions: "Ngoại lệ bot",
      noField: "Không có field kỹ thuật.",
      editDetail: "Chi tiết vận hành",
      readDetail: "Chi tiết nhật ký"
    },
    scam: {
      eyebrow: "Anti scam",
      title: "Duyệt report",
      body: "Cập nhật hồ sơ.",
      pending: "report chờ",
      waiting: "Chờ duyệt",
      confirmed: "Đã xác nhận",
      rejected: "Đã từ chối",
      bot: "Bot",
      queue: "Hàng đợi",
      priority: "Ưu tiên mới.",
      open: "Mở",
      review: "Duyệt",
      profile: "Hồ sơ",
      noPending: "Không còn report pending.",
      report: "Report",
      targetUnknown: "Chưa rõ",
      hasEvidence: "Có bằng chứng",
      noEvidence: "Thiếu bằng chứng"
    },
    bot: {
      eyebrow: "Bot",
      title: "Kết nối bot",
      body: "Kiểm tra trạng thái.",
      done: "điều kiện xong",
      connect: "Kết nối",
      permissions: "Quyền",
      module: "Module",
      token: "Token, trạng thái.",
      ownerMod: "Owner, mod.",
      viewModules: "Xem module.",
      doneCount: "điều kiện xong"
    },
    group: {
      eyebrow: "Group",
      title: "Phạm vi",
      body: "Chọn group và quyền.",
      statusReady: "Sẵn sàng",
      statusCheck: "Cần kiểm tra",
      unselected: "Chưa chọn",
      group: "Group",
      permissions: "Quyền",
      module: "Module",
      addGroup: "Thêm group.",
      botRole: "Bot và role.",
      viewModules: "Xem module.",
      check: "Cần kiểm tra"
    }
  },
  inspector: {
    runtime: "Runtime",
    noField: "Không có field kỹ thuật.",
    editDetail: "Chi tiết vận hành",
    readDetail: "Chi tiết nhật ký",
    step: "Bước sau",
    test: "Test",
    testReady: "Test UI đã sẵn sàng."
  }
} as const;
